function compile_mex_gsc
%compile_mex_gsc compiles the MEX-function taken from the GSC package
%
% Anton Osokin

rootDir = fileparts( mfilename( 'fullpath' ) );
cppDir = fullfile( rootDir, 'cpp' );

mexFiles = { 'mex_setupTransductionGraph.cpp', ...
             'vag_norm_fast.cpp', ...
             'mex_mapEdges.cpp', ...
             'mex_spNormalized_constrained.cpp' };
         
targetFiles = { 'mex_setupTransductionGraph', ...
                'vag_norm_fast', ...
                'mex_mapEdges', ...
                'mex_spNormalized_constrained' };         
numFiles = length( mexFiles );            
for iFile = 1 : numFiles
    mex( '-O', fullfile( cppDir, mexFiles{iFile} ), ...
         '-output', fullfile( rootDir, targetFiles{iFile} ), ...
         '-largeArrayDims' );
end

end
